### ISSUE TITLE
A validação de email deixa passar casos inválidos

### ISSUE THREAD

**Issue by JCDMeira** [MarcoFranca/Pod-request-access-landing-page#2]
A validação de e-mail deixa passar casos como "teste@test"
Não da pra ver ao certo o que aparece no console, mas a tela da reload. Aparentemente deixando passar essa resposta

**Comment by MarcoFranca** [comment]
inclusão do event.preventdefault() no if de validação do email para correção do problema de envio de emails #1 #2
